[project]
name = "artref"
version = "0.1.0"
description = ""
requires-python = ">=3.7"
dependencies = [
  "aiocache",
  "aiohttp",
  "diskcache",
  "dotenv",
  "fastapi",
  "pytest",
  "typer",
  "uvicorn",
]

[project.scripts]
artref = "artref.main:main"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest]
pythonpath = ["src"]
testpaths = ["tests"]
